server {

  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location ~ \.mjs$ {
    types { }
    default_type text/javascript;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
